<a href="https://colab.research.google.com/github/SwimLane2/udacity-ai-masters/blob/main/AI%20Programming%20with%20Python/numpy/broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Broadcasting**

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [1]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b


array([2., 4., 6.])

In [2]:

a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [3]:

a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b
# b = np.array([1.0, 2.0, 3.0, 4.0])
# a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

Use Broadcasting to create a ** 4 x 4 ndarray** that has

- first column full of 1s
- second column full of 2s
- third column full of 3s, etc..

In [4]:
import numpy as np

# Replace None with appropriate code
X = np.ones((4,4)) * np.arange(1,5)

print(np.ones((4,4)))
print(np.arange(1,5))

### Notebook grading
solution = np.ones((4,4)) * np.arange(1,5)
if type(X) != np.ndarray:
    print("`X` should be an ndarray")
elif np.array_equal(X, solution):
    print("Nice work! You can view my solution below")
elif X.shape != solution.shape:
    print("Your answer for `X` has a shape of {} but it should be 4 x 4".format(X.shape))
else:
    print("Your answer for `X` has the right shape but incorrect values")

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 2 3 4]
Nice work! You can view my solution below
