<a href="https://colab.research.google.com/github/SwimLane2/udacity-ai-masters/blob/main/AI%20Programming%20with%20Python/Introduction-to-transformer-neural-networks/01_torch_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [ ]:
## torch.rand()

In [2]:
torch.rand(5)

tensor([0.2946, 0.5083, 0.9489, 0.5768, 0.9198])

In [3]:
torch.rand(5, 5)

tensor([[0.5549, 0.7670, 0.0091, 0.7126, 0.8438],
        [0.9677, 0.5287, 0.0463, 0.0830, 0.3392],
        [0.3786, 0.5163, 0.2266, 0.1600, 0.7543],
        [0.0578, 0.4497, 0.5565, 0.9757, 0.5534],
        [0.1981, 0.5391, 0.7077, 0.6628, 0.1854]])

In [ ]:
## torch.ones

In [4]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [6]:
torch.ones(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
## torch.arange

In [7]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## torch.tril

In [8]:
torch.tril(torch.rand(5, 5))

tensor([[0.7273, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.7263, 0.3872, 0.0000, 0.0000, 0.0000],
        [0.9179, 0.0716, 0.5789, 0.0000, 0.0000],
        [0.7862, 0.8597, 0.5255, 0.4292, 0.0000],
        [0.9251, 0.7199, 0.3128, 0.2708, 0.9319]])

In [ ]:
## torch.cat

In [9]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

In [10]:
# Concatenate along rows
torch.cat((tensor_a, tensor_b), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [11]:
# Concatenate along columns
torch.cat((tensor_a, tensor_b), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [ ]:
## tensor.view()

In [12]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
x_reshaped = x.view(3, 4)
x_reshaped

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
x_reshaped.view(12)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])