<a href="https://colab.research.google.com/github/SwimLane2/udacity-ai-masters/blob/main/AI%20Programming%20with%20Python/Introduction-to-transformer-neural-networks/01_torch_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
## torch.rand()

In [ ]:
torch.rand(5)

tensor([0.0172, 0.3152, 0.1039, 0.0559, 0.4318])

In [ ]:
torch.rand(5, 5)

tensor([[0.3005, 0.5307, 0.0506, 0.7799, 0.5718],
        [0.5960, 0.6300, 0.8936, 0.3779, 0.6295],
        [0.6082, 0.5375, 0.3223, 0.7011, 0.4415],
        [0.2314, 0.7563, 0.2230, 0.2633, 0.0657],
        [0.3942, 0.3352, 0.2214, 0.2713, 0.4043]])

In [ ]:
## torch.ones

In [ ]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [ ]:
torch.ones(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
## torch.arange

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## torch.tril

In [ ]:
torch.tril(torch.rand(5, 5))

tensor([[0.8449, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1169, 0.4584, 0.0000, 0.0000, 0.0000],
        [0.0051, 0.2800, 0.7516, 0.0000, 0.0000],
        [0.9991, 0.2521, 0.1827, 0.7836, 0.0000],
        [0.4891, 0.2556, 0.5963, 0.0570, 0.6635]])

In [ ]:
## torch.cat

In [ ]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

In [ ]:
# Concatenate along rows
torch.cat((tensor_a, tensor_b), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
# Concatenate along columns
torch.cat((tensor_a, tensor_b), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [ ]:
## tensor.view()

In [ ]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x_reshaped = x.view(3, 4)
x_reshaped

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
x_reshaped.view(12)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])