<a href="https://colab.research.google.com/github/SwimLane2/udacity-ai-masters/blob/main/numpy/Using%20Built-in%20Functions%20to%20Create%20ndarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# We create a 3 x 4 ndarray full of zeros.
import numpy as np
X = np.zeros((3,4))
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
X = np.ones((3,2))
print(X)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
X = np.diag([10, 20, 30])
print(X)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [10]:
X = np.arange(4, 10, 2)
print(X)

[4 6 8]


In [11]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [12]:
x = np.linspace(0, 25, 10, endpoint = False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [17]:
x = np.arange(30)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [20]:
x = np.reshape(x, (5, 6))
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [21]:
x = np.random.random((3,3))
print(x)

[[0.15431851 0.77895422 0.09215389]
 [0.79803251 0.55992799 0.43093581]
 [0.48818001 0.33496454 0.80492989]]


In [22]:
x = np.random.randint(4, 15, (3,2))
print(x)

[[10  8]
 [ 7  7]
 [ 9  9]]


In [23]:
x = np.random.normal(0, 0.1, size=(1000,1000))
print(x)

[[-0.0453028   0.06226954  0.11255892 ... -0.05517966  0.01945246
  -0.05514337]
 [-0.03462071 -0.09728022  0.10693752 ... -0.18068863 -0.08657648
   0.04204664]
 [-0.10211267  0.15217806  0.0652938  ... -0.04651312  0.01318206
  -0.01963463]
 ...
 [ 0.08803492  0.22459104  0.07561972 ... -0.00209072  0.21463962
  -0.04779421]
 [ 0.04434351 -0.01573365  0.1903989  ... -0.00321789 -0.12127342
   0.21826577]
 [ 0.14955401 -0.23404451 -0.16296514 ... -0.04319497 -0.03681168
  -0.1457477 ]]
